// import Image from "next/image";
import { BaseButton } from "./components/BaseButton";
import { BaseContainer } from "./components/BaseContainer";

export default function Home() {
  return (
    <BaseContainer
      classNamePortraitFlex="portrait:flex-row"
      classNameLandscapeFlex="landscape:flex-col"
      classNamePortraitW="portrait:w-[100dvw]"
      classNamePortraitH="portrait:h-[100dvh]"
      classNameLandscapeW="landscape:w-[100dvw]"
      classNameLandscapeH="landscape:h-[100dvh]"
      classNamePX="px-[2dvw]"
      classNamePY="py-[2dvh]"
    >
      <BaseContainer
        classNamePortraitFlex="portrait:flex-col"
        classNameLandscapeFlex="landscape:flex-row"
        classNamePortraitW="portrait:w-[36.85dvw]"
        classNamePortraitH="portrait:h-[96dvh]"
        classNameLandscapeW="landscape:w-[96dvw]"
        classNameLandscapeH="landscape:h-[36.85dvh]"
        classNamePX="px-0"
        classNamePY="py-0"
      >
        <BaseContainer
          classNamePortraitFlex="portrait:flex-row"
          classNameLandscapeFlex="landscape:flex-col"
          classNamePortraitW="portrait:w-[36.85dvw]"
          classNamePortraitH="portrait:h-[54dvh]"
          classNameLandscapeW="landscape:w-[54dvw]"
          classNameLandscapeH="landscape:h-[36.85dvh]"
          classNamePX="px-0"
          classNamePY="py-0"
        >
          <BaseContainer
            classNamePortraitFlex="portrait:flex-col"
            classNameLandscapeFlex="landscape:flex-row"
            classNamePortraitW="portrait:w-[10.95dvw]"
            classNamePortraitH="portrait:h-[54dvh]"
            classNameLandscapeW="landscape:w-[54dvw]"
            classNameLandscapeH="landscape:h-[10.95dvh]"
            classNamePX="px-0"
            classNamePY="py-0"
          >
            <BaseButton
              classNamePortraitW="portrait:w-[10.95dvw]"
              classNamePortraitH="portrait:h-[12dvh]"
              classNameLandscapeW="landscape:w-[12dvw]"
              classNameLandscapeH="landscape:h-[10.95dvh]"
              classNameBg="bg-amber-600"
            >
              1
            </BaseButton>
            <BaseButton
              classNamePortraitW="portrait:w-[10.95dvw]"
              classNamePortraitH="portrait:h-[12dvh]"
              classNameLandscapeW="landscape:w-[12dvw]"
              classNameLandscapeH="landscape:h-[10.95dvh]"
              classNameBg="bg-amber-600"
            >
              2
            </BaseButton>
            <BaseButton
              classNamePortraitW="portrait:w-[10.95dvw]"
              classNamePortraitH="portrait:h-[12dvh]"
              classNameLandscapeW="landscape:w-[12dvw]"
              classNameLandscapeH="landscape:h-[10.95dvh]"
              classNameBg="bg-amber-600"
            >
              3
            </BaseButton>
            <BaseButton
              classNamePortraitW="portrait:w-[10.95dvw]"
              classNamePortraitH="portrait:h-[12dvh]"
              classNameLandscapeW="landscape:w-[12dvw]"
              classNameLandscapeH="landscape:h-[10.95dvh]"
              classNameBg="bg-amber-600"
            >
              4
            </BaseButton>
          </BaseContainer>
          <BaseContainer
            classNamePortraitFlex="portrait:flex-row-reverse"
            classNameLandscapeFlex="landscape:flex-col"
            classNamePortraitW="portrait:w-[23.9dvw]"
            classNamePortraitH="portrait:h-[54dvh]"
            classNameLandscapeW="landscape:w-[54dvw]"
            classNameLandscapeH="landscape:h-[23.9dvh]"
            classNamePX="px-0"
            classNamePY="py-0"
          >
            <BaseContainer
              classNamePortraitFlex="portrait:flex-col-reverse"
              classNameLandscapeFlex="landscape:flex-row"
              classNamePortraitW="portrait:w-[10.95dvw]"
              classNamePortraitH="portrait:h-[54dvh]"
              classNameLandscapeW="landscape:w-[54dvw]"
              classNameLandscapeH="landscape:h-[10.95dvh]"
              classNamePX="px-0"
              classNamePY="py-0"
            >
              <BaseButton
                classNamePortraitW="portrait:w-[10.95dvw]"
                classNamePortraitH="portrait:h-[12dvh]"
                classNameLandscapeW="landscape:w-[12dvw]"
                classNameLandscapeH="landscape:h-[10.95dvh]"
                classNameBg="bg-gray-600"
              >
                1
              </BaseButton>
              <BaseButton
                classNamePortraitW="portrait:w-[10.95dvw]"
                classNamePortraitH="portrait:h-[12dvh]"
                classNameLandscapeW="landscape:w-[12dvw]"
                classNameLandscapeH="landscape:h-[10.95dvh]"
                classNameBg="bg-gray-600"
              >
                2
              </BaseButton>
              <BaseButton
                classNamePortraitW="portrait:w-[10.95dvw]"
                classNamePortraitH="portrait:h-[12dvh]"
                classNameLandscapeW="landscape:w-[12dvw]"
                classNameLandscapeH="landscape:h-[10.95dvh]"
                classNameBg="bg-gray-600"
              >
                3
              </BaseButton>
              <BaseButton
                classNamePortraitW="portrait:w-[10.95dvw]"
                classNamePortraitH="portrait:h-[12dvh]"
                classNameLandscapeW="landscape:w-[12dvw]"
                classNameLandscapeH="landscape:h-[10.95dvh]"
                classNameBg="bg-gray-600"
              >
                4
              </BaseButton>
            </BaseContainer>
            <BaseContainer
              classNamePortraitFlex="portrait:flex-col-reverse"
              classNameLandscapeFlex="landscape:flex-row"
              classNamePortraitW="portrait:w-[10.95dvw]"
              classNamePortraitH="portrait:h-[54dvh]"
              classNameLandscapeW="landscape:w-[54dvw]"
              classNameLandscapeH="landscape:h-[10.95dvh]"
              classNamePX="px-0"
              classNamePY="py-0"
            >
              <BaseButton
                classNamePortraitW="portrait:w-[10.95dvw]"
                classNamePortraitH="portrait:h-[12dvh]"
                classNameLandscapeW="landscape:w-[12dvw]"
                classNameLandscapeH="landscape:h-[10.95dvh]"
                classNameBg="bg-lime-600"
              >
                1
              </BaseButton>
              <BaseButton
                classNamePortraitW="portrait:w-[10.95dvw]"
                classNamePortraitH="portrait:h-[12dvh]"
                classNameLandscapeW="landscape:w-[12dvw]"
                classNameLandscapeH="landscape:h-[10.95dvh]"
                classNameBg="bg-lime-600"
              >
                2
              </BaseButton>
              <BaseButton
                classNamePortraitW="portrait:w-[10.95dvw]"
                classNamePortraitH="portrait:h-[12dvh]"
                classNameLandscapeW="landscape:w-[12dvw]"
                classNameLandscapeH="landscape:h-[10.95dvh]"
                classNameBg="bg-lime-600"
              >
                3
              </BaseButton>
              <BaseButton
                classNamePortraitW="portrait:w-[10.95dvw]"
                classNamePortraitH="portrait:h-[12dvh]"
                classNameLandscapeW="landscape:w-[12dvw]"
                classNameLandscapeH="landscape:h-[10.95dvh]"
                classNameBg="bg-lime-600"
              >
                4
              </BaseButton>
            </BaseContainer>
          </BaseContainer>
        </BaseContainer>
        <BaseContainer
          classNamePortraitFlex="portrait:flex-col"
          classNameLandscapeFlex="landscape:flex-col"
          classNamePortraitW="portrait:w-[36.85dvw]"
          classNamePortraitH="portrait:h-[40dvh]"
          classNameLandscapeW="landscape:w-[40dvw]"
          classNameLandscapeH="landscape:h-[36.85dvh]"
          classNamePX="px-0"
          classNamePY="py-0"
        >
          <BaseContainer
            classNamePortraitFlex="portrait:flex-row"
            classNameLandscapeFlex="landscape:flex-row"
            classNamePortraitW="portrait:w-[36.85dvw]"
            classNamePortraitH="portrait:h-[12dvh]"
            classNameLandscapeW="landscape:w-[40dvw]"
            classNameLandscapeH="landscape:h-[10.95dvh]"
            classNamePX="px-0"
            classNamePY="py-0"
          >
            <BaseButton
              classNamePortraitW="portrait:w-[10.95dvw]"
              classNamePortraitH="portrait:h-[12dvh]"
              classNameLandscapeW="landscape:w-[12dvw]"
              classNameLandscapeH="landscape:h-[10.95dvh]"
              classNameBg="bg-fuchsia-600"
            >
              1
            </BaseButton>
            <BaseButton
              classNamePortraitW="portrait:w-[10.95dvw]"
              classNamePortraitH="portrait:h-[12dvh]"
              classNameLandscapeW="landscape:w-[12dvw]"
              classNameLandscapeH="landscape:h-[10.95dvh]"
              classNameBg="bg-fuchsia-600"
            >
              2
            </BaseButton>
            <BaseButton
              classNamePortraitW="portrait:w-[10.95dvw]"
              classNamePortraitH="portrait:h-[12dvh]"
              classNameLandscapeW="landscape:w-[12dvw]"
              classNameLandscapeH="landscape:h-[10.95dvh]"
              classNameBg="bg-fuchsia-600"
            >
              3
            </BaseButton>
          </BaseContainer>
          <BaseContainer
            classNamePortraitFlex="portrait:flex-row"
            classNameLandscapeFlex="landscape:flex-row"
            classNamePortraitW="portrait:w-[36.85dvw]"
            classNamePortraitH="portrait:h-[12dvh]"
            classNameLandscapeW="landscape:w-[40dvw]"
            classNameLandscapeH="landscape:h-[10.95dvh]"
            classNamePX="px-0"
            classNamePY="py-0"
          >
            <BaseButton
              classNamePortraitW="portrait:w-[10.95dvw]"
              classNamePortraitH="portrait:h-[12dvh]"
              classNameLandscapeW="landscape:w-[12dvw]"
              classNameLandscapeH="landscape:h-[10.95dvh]"
              classNameBg="bg-rose-600"
            >
              1
            </BaseButton>
            <BaseButton
              classNamePortraitW="portrait:w-[10.95dvw]"
              classNamePortraitH="portrait:h-[12dvh]"
              classNameLandscapeW="landscape:w-[12dvw]"
              classNameLandscapeH="landscape:h-[10.95dvh]"
              classNameBg="bg-rose-600"
            >
              2
            </BaseButton>
            <BaseButton
              classNamePortraitW="portrait:w-[10.95dvw]"
              classNamePortraitH="portrait:h-[12dvh]"
              classNameLandscapeW="landscape:w-[12dvw]"
              classNameLandscapeH="landscape:h-[10.95dvh]"
              classNameBg="bg-rose-600"
            >
              3
            </BaseButton>
          </BaseContainer>
          <BaseContainer
            classNamePortraitFlex="portrait:flex-row"
            classNameLandscapeFlex="landscape:flex-row"
            classNamePortraitW="portrait:w-[36.85dvw]"
            classNamePortraitH="portrait:h-[12dvh]"
            classNameLandscapeW="landscape:w-[40dvw]"
            classNameLandscapeH="landscape:h-[10.95dvh]"
            classNamePX="px-0"
            classNamePY="py-0"
          >
            <BaseButton
              classNamePortraitW="portrait:w-[10.95dvw]"
              classNamePortraitH="portrait:h-[12dvh]"
              classNameLandscapeW="landscape:w-[12dvw]"
              classNameLandscapeH="landscape:h-[10.95dvh]"
              classNameBg="bg-blue-600"
            >
              1
            </BaseButton>
            <BaseButton
              classNamePortraitW="portrait:w-[10.95dvw]"
              classNamePortraitH="portrait:h-[12dvh]"
              classNameLandscapeW="landscape:w-[12dvw]"
              classNameLandscapeH="landscape:h-[10.95dvh]"
              classNameBg="bg-blue-600"
            >
              2
            </BaseButton>
            <BaseButton
              classNamePortraitW="portrait:w-[10.95dvw]"
              classNamePortraitH="portrait:h-[12dvh]"
              classNameLandscapeW="landscape:w-[12dvw]"
              classNameLandscapeH="landscape:h-[10.95dvh]"
              classNameBg="bg-blue-600"
            >
              3
            </BaseButton>
          </BaseContainer>
        </BaseContainer>
      </BaseContainer>
      <BaseContainer
        classNamePortraitFlex="portrait:flex-row-reverse"
        classNameLandscapeFlex="landscape:flex-col"
        classNamePortraitW="portrait:w-[56.6dvw]"
        classNamePortraitH="portrait:h-[96dvh]"
        classNameLandscapeW="landscape:w-[96dvw]"
        classNameLandscapeH="landscape:h-[56.6dvh]"
        classNamePX="px-0"
        classNamePY="py-0"
      >
        <BaseContainer
          classNamePortraitFlex="portrait:flex-col-reverse"
          classNameLandscapeFlex="landscape:flex-row"
          classNamePortraitW="portrait:w-[17.2dvw]"
          classNamePortraitH="portrait:h-[96dvh]"
          classNameLandscapeW="landscape:w-[96dvw]"
          classNameLandscapeH="landscape:h-[17.2dvh]"
          classNamePX="px-0"
          classNamePY="py-0"
        >
          <BaseButton
            classNamePortraitW="portrait:w-[17.2dvw]"
            classNamePortraitH="portrait:h-[12dvh]"
            classNameLandscapeW="landscape:w-[12dvw]"
            classNameLandscapeH="landscape:h-[17.2dvh]"
            classNameBg="bg-teal-600"
          >
            15
          </BaseButton>
          <BaseButton
            classNamePortraitW="portrait:w-[17.2dvw]"
            classNamePortraitH="portrait:h-[12dvh]"
            classNameLandscapeW="landscape:w-[12dvw]"
            classNameLandscapeH="landscape:h-[17.2dvh]"
            classNameBg="bg-teal-600"
          >
            16
          </BaseButton>{" "}
          <BaseButton
            classNamePortraitW="portrait:w-[17.2dvw]"
            classNamePortraitH="portrait:h-[12dvh]"
            classNameLandscapeW="landscape:w-[12dvw]"
            classNameLandscapeH="landscape:h-[17.2dvh]"
            classNameBg="bg-teal-600"
          >
            17
          </BaseButton>{" "}
          <BaseButton
            classNamePortraitW="portrait:w-[17.2dvw]"
            classNamePortraitH="portrait:h-[12dvh]"
            classNameLandscapeW="landscape:w-[12dvw]"
            classNameLandscapeH="landscape:h-[17.2dvh]"
            classNameBg="bg-teal-600"
          >
            18
          </BaseButton>{" "}
          <BaseButton
            classNamePortraitW="portrait:w-[17.2dvw]"
            classNamePortraitH="portrait:h-[12dvh]"
            classNameLandscapeW="landscape:w-[12dvw]"
            classNameLandscapeH="landscape:h-[17.2dvh]"
            classNameBg="bg-teal-600"
          >
            19
          </BaseButton>{" "}
          <BaseButton
            classNamePortraitW="portrait:w-[17.2dvw]"
            classNamePortraitH="portrait:h-[12dvh]"
            classNameLandscapeW="landscape:w-[12dvw]"
            classNameLandscapeH="landscape:h-[17.2dvh]"
            classNameBg="bg-teal-600"
          >
            20
          </BaseButton>{" "}
          <BaseButton
            classNamePortraitW="portrait:w-[17.2dvw]"
            classNamePortraitH="portrait:h-[12dvh]"
            classNameLandscapeW="landscape:w-[12dvw]"
            classNameLandscapeH="landscape:h-[17.2dvh]"
            classNameBg="bg-teal-600"
          >
            21
          </BaseButton>
        </BaseContainer>
        <BaseContainer
          classNamePortraitFlex="portrait:flex-col-reverse"
          classNameLandscapeFlex="landscape:flex-row"
          classNamePortraitW="portrait:w-[17.2dvw]"
          classNamePortraitH="portrait:h-[96dvh]"
          classNameLandscapeW="landscape:w-[96dvw]"
          classNameLandscapeH="landscape:h-[17.2dvh]"
          classNamePX="px-0"
          classNamePY="py-0"
        >
          <BaseButton
            classNamePortraitW="portrait:w-[17.2dvw]"
            classNamePortraitH="portrait:h-[12dvh]"
            classNameLandscapeW="landscape:w-[12dvw]"
            classNameLandscapeH="landscape:h-[17.2dvh]"
            classNameBg="bg-teal-600"
          >
            8
          </BaseButton>
          <BaseButton
            classNamePortraitW="portrait:w-[17.2dvw]"
            classNamePortraitH="portrait:h-[12dvh]"
            classNameLandscapeW="landscape:w-[12dvw]"
            classNameLandscapeH="landscape:h-[17.2dvh]"
            classNameBg="bg-teal-600"
          >
            9
          </BaseButton>{" "}
          <BaseButton
            classNamePortraitW="portrait:w-[17.2dvw]"
            classNamePortraitH="portrait:h-[12dvh]"
            classNameLandscapeW="landscape:w-[12dvw]"
            classNameLandscapeH="landscape:h-[17.2dvh]"
            classNameBg="bg-teal-600"
          >
            10
          </BaseButton>{" "}
          <BaseButton
            classNamePortraitW="portrait:w-[17.2dvw]"
            classNamePortraitH="portrait:h-[12dvh]"
            classNameLandscapeW="landscape:w-[12dvw]"
            classNameLandscapeH="landscape:h-[17.2dvh]"
            classNameBg="bg-teal-600"
          >
            11
          </BaseButton>{" "}
          <BaseButton
            classNamePortraitW="portrait:w-[17.2dvw]"
            classNamePortraitH="portrait:h-[12dvh]"
            classNameLandscapeW="landscape:w-[12dvw]"
            classNameLandscapeH="landscape:h-[17.2dvh]"
            classNameBg="bg-teal-600"
          >
            12
          </BaseButton>{" "}
          <BaseButton
            classNamePortraitW="portrait:w-[17.2dvw]"
            classNamePortraitH="portrait:h-[12dvh]"
            classNameLandscapeW="landscape:w-[12dvw]"
            classNameLandscapeH="landscape:h-[17.2dvh]"
            classNameBg="bg-teal-600"
          >
            13
          </BaseButton>{" "}
          <BaseButton
            classNamePortraitW="portrait:w-[17.2dvw]"
            classNamePortraitH="portrait:h-[12dvh]"
            classNameLandscapeW="landscape:w-[12dvw]"
            classNameLandscapeH="landscape:h-[17.2dvh]"
            classNameBg="bg-teal-600"
          >
            14
          </BaseButton>
        </BaseContainer>
        <BaseContainer
          classNamePortraitFlex="portrait:flex-col-reverse"
          classNameLandscapeFlex="landscape:flex-row"
          classNamePortraitW="portrait:w-[17.2dvw]"
          classNamePortraitH="portrait:h-[96dvh]"
          classNameLandscapeW="landscape:w-[96dvw]"
          classNameLandscapeH="landscape:h-[17.2dvh]"
          classNamePX="px-0"
          classNamePY="py-0"
        >
          <BaseButton
            classNamePortraitW="portrait:w-[17.2dvw]"
            classNamePortraitH="portrait:h-[12dvh]"
            classNameLandscapeW="landscape:w-[12dvw]"
            classNameLandscapeH="landscape:h-[17.2dvh]"
            classNameBg="bg-teal-600"
          >
            1
          </BaseButton>
          <BaseButton
            classNamePortraitW="portrait:w-[17.2dvw]"
            classNamePortraitH="portrait:h-[12dvh]"
            classNameLandscapeW="landscape:w-[12dvw]"
            classNameLandscapeH="landscape:h-[17.2dvh]"
            classNameBg="bg-teal-600"
          >
            2
          </BaseButton>{" "}
          <BaseButton
            classNamePortraitW="portrait:w-[17.2dvw]"
            classNamePortraitH="portrait:h-[12dvh]"
            classNameLandscapeW="landscape:w-[12dvw]"
            classNameLandscapeH="landscape:h-[17.2dvh]"
            classNameBg="bg-teal-600"
          >
            3
          </BaseButton>{" "}
          <BaseButton
            classNamePortraitW="portrait:w-[17.2dvw]"
            classNamePortraitH="portrait:h-[12dvh]"
            classNameLandscapeW="landscape:w-[12dvw]"
            classNameLandscapeH="landscape:h-[17.2dvh]"
            classNameBg="bg-teal-600"
          >
            4
          </BaseButton>{" "}
          <BaseButton
            classNamePortraitW="portrait:w-[17.2dvw]"
            classNamePortraitH="portrait:h-[12dvh]"
            classNameLandscapeW="landscape:w-[12dvw]"
            classNameLandscapeH="landscape:h-[17.2dvh]"
            classNameBg="bg-teal-600"
          >
            5
          </BaseButton>{" "}
          <BaseButton
            classNamePortraitW="portrait:w-[17.2dvw]"
            classNamePortraitH="portrait:h-[12dvh]"
            classNameLandscapeW="landscape:w-[12dvw]"
            classNameLandscapeH="landscape:h-[17.2dvh]"
            classNameBg="bg-teal-600"
          >
            6
          </BaseButton>{" "}
          <BaseButton
            classNamePortraitW="portrait:w-[17.2dvw]"
            classNamePortraitH="portrait:h-[12dvh]"
            classNameLandscapeW="landscape:w-[12dvw]"
            classNameLandscapeH="landscape:h-[17.2dvh]"
            classNameBg="bg-teal-600"
          >
            7
          </BaseButton>
        </BaseContainer>
      </BaseContainer>
    </BaseContainer>
  );
}
